import type { CollectionConfig } from 'payload'

import { anyone } from '../access/anyone'
import { authenticated } from '../access/authenticated'
import { slugField } from 'payload'

export const ProductCategories: CollectionConfig = {
  slug: 'product-categories',
  access: {
    create: authenticated,
    delete: authenticated,
    read: anyone,
    update: authenticated,
  },
  admin: {
    // 'name' drives the admin list view title AND the breadcrumb label
    // generated by nestedDocsPlugin (plugin reads collection.admin.useAsTitle at runtime).
    useAsTitle: 'name',
    defaultColumns: ['name', 'slug', 'parent', 'updatedAt'],
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
    // slugField defaults useAsSlug to 'title'; override to 'name'.
    // position: undefined keeps it in the main form body (not sidebar).
    slugField({
      useAsSlug: 'name',
      position: undefined,
    }),
    {
      name: 'description',
      type: 'text',
    },
    {
      name: 'image',
      type: 'upload',
      relationTo: 'media',
    },
    {
      name: 'color',
      type: 'text',
      admin: {
        description: 'Hex color code, e.g. #3B82F6',
      },
    },
    {
      name: 'sortOrder',
      type: 'number',
      min: 0,
      admin: {
        description: 'Display order among siblings at the same level. Lower = first.',
        step: 1,
      },
    },
    // NOTE: 'parent' and 'breadcrumbs' fields are injected automatically
    // by nestedDocsPlugin at startup. Do not define them here.
  ],
}
