import {
  Activity,
  BarChart,
  Bolt,
  ChartBarIncreasingIcon,
  CheckCircle,
  Cloud,
  Code,
  Cpu,
  Database,
  Fingerprint,
  Globe,
  IdCard,
  Layers,
  Lock,
  Map,
  MessageCircle,
  Pencil,
  Rocket,
  RefreshCw,
  Settings,
  Settings2,
  Shield,
  Sparkles,
  Star,
  Users,
  Zap,
} from 'lucide-react'
import React from 'react'

export const iconMap: Record<string, React.FC<{ className?: string }>> = {
  Activity,
  BarChart,
  Bolt,
  ChartBarIncreasing: ChartBarIncreasingIcon,
  CheckCircle,
  Cloud,
  Code,
  Cpu,
  Database,
  Fingerprint,
  Globe,
  IdCard,
  Layers,
  Lock,
  Map,
  MessageCircle,
  Pencil,
  Rocket,
  RefreshCw,
  Settings,
  Settings2,
  Shield,
  Sparkles,
  Star,
  Users,
  Zap,
}

export const ICON_OPTIONS = [
  { label: 'Activity', value: 'Activity' },
  { label: 'Bar Chart', value: 'BarChart' },
  { label: 'Bolt', value: 'Bolt' },
  { label: 'Chart Bar Increasing', value: 'ChartBarIncreasing' },
  { label: 'Check Circle', value: 'CheckCircle' },
  { label: 'Cloud', value: 'Cloud' },
  { label: 'Code', value: 'Code' },
  { label: 'CPU', value: 'Cpu' },
  { label: 'Database', value: 'Database' },
  { label: 'Fingerprint', value: 'Fingerprint' },
  { label: 'Globe', value: 'Globe' },
  { label: 'ID Card', value: 'IdCard' },
  { label: 'Layers', value: 'Layers' },
  { label: 'Lock', value: 'Lock' },
  { label: 'Map', value: 'Map' },
  { label: 'Message Circle', value: 'MessageCircle' },
  { label: 'Pencil', value: 'Pencil' },
  { label: 'Refresh', value: 'RefreshCw' },
  { label: 'Rocket', value: 'Rocket' },
  { label: 'Settings', value: 'Settings' },
  { label: 'Settings 2', value: 'Settings2' },
  { label: 'Shield', value: 'Shield' },
  { label: 'Sparkles', value: 'Sparkles' },
  { label: 'Star', value: 'Star' },
  { label: 'Users', value: 'Users' },
  { label: 'Zap', value: 'Zap' },
]
